/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
export const beers = [
  {
    id: 1,
    type: "Cerveza",
    title: "Estrella Damm",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza1.png" ,
    text: "De ingredientes 100% naturales, sin aditivos ni conservantes. “Estrella Damm” maltea la cebada en su propia maltería lo que les permite controlar todo el proceso, además trabajan directamente con los agricultores asegurando así la calidad de los ingredientes usados en la cerveza. Su espuma es de color crudo y tiene larga presencia, es una cerveza dorada con ciertas tonalidades ambarinas. Se siente en su sabor notas a cereales tostados." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 2,
    type: "Cerveza",
    title: "Marantá",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza2.png" ,
    text: "”Bayo” es de color naranja pálido, ligera y con notas cítricas, algo seca y de impresión suave y esponjosa. Es ideal para maridar con pollo, pescados, mariscos y quesos semi duros." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 3,
    type: "Cerveza",
    title: "Becks",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza3.png" ,
    text: "De sabor equilibrado, dulce y suave, es de color dorado y tiene aromas florales y afrutados. Al ser elaborada bajo la ley de pureza alemana, sus ingredientes son seleccionaos bajo los estándares más altos y estrictos de calidad." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 4,
    type: "Cerveza",
    title: "Bitburger",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza4.png" ,
    text: "Es una de las cervezas 🍺 más vendidas de Alemania 🇩🇪, es poco amarga y de sabor no muy intenso, es popular por su final seco y por el sabor del lúpulo que la hacen una verdadera representante de las cervezas rubias alemanas. Es ideal para tomar en cualquier momento del día." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 5,
    type: "Cerveza",
    title: "Maredsous",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza5.png" ,
    text: "Es una cerveza abadía de color rubio y de alta fermentación. Es la más ligera y refrescante de las 3 cervezas “Maredsous”. Su botella permite servirla con una capa de espuma, es ideal para acompañar con pescados blancos, mejillones o almejas." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 6,
    type: "Cerveza",
    title: "Erdinger",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza6.png" ,
    text: "Se elabora a base de trigo, maltas oscuras y lúpulos finos. Es de color marrón oscuro y tiene una espuma alta y blanca a la hora de servirse. Es una cerveza ideal para tomarse a los 6º - 8ºC de temperatura, es de alta fermentación con “Doble fermentación”. La 1ra se hace durante su proceso de elaboración, la 2da se hace en la propia botella. En Colombia, la puedes conseguirla en las tiendas Jumbo." ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 6,
    type: "Cerveza",
    title: "3 Cordilleras",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza7.png" ,
    text: "🍻Cerveza estilo Amber Ale color rojo intenso, tiene variedades de maltas que hacen que en boca se sienta un toque tostado y acaramelado con un final amaderado. Su sabor es menos fuerte y más dulce de lo que se espera." ,
    ingredients: [""],
    steps: [""],
  },
]