/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
export const beers = [
  {
    id: 1,
    type: "Cerveza",
    title: "Estrella Damm",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza1.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 2,
    type: "Cerveza",
    title: "Marantá",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza2.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 3,
    type: "Cerveza",
    title: "Becks",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza3.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 4,
    type: "Cerveza",
    title: "Bitburger",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza4.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 5,
    type: "Cerveza",
    title: "Maredsous",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza5.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 6,
    type: "Cerveza",
    title: "Erdinger",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza6.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
  {
    id: 6,
    type: "Cerveza",
    title: "3 Cordilleras",
    image: "http://www.gecsas.com.co/ImagesECommerce/Cerveza/Cerveza7.png" ,
    text: "" ,
    ingredients: [""],
    steps: [""],
  },
]